name = "rinha_2024_q1_ada"
description = "Projeto participante da Rinha 2024 Q1"
version = "0.1.0-dev"

authors = ["Marco Damaceno"]
maintainers = ["Marco Damaceno <maadamaceno@gmail.com>"]
maintainers-logins = ["mdamaceno"]

executables = ["rinha_2024_q1_ada"]
[[depends-on]]
aws = "^23.0.0"
[[depends-on]]
utilada = "^2.6.0"
[[depends-on]]
gnatcoll_postgres = "^23.0.0"
