version: '3.9'

services:
  db:
    image: postgres:16-alpine
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha2024
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - rinha-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 7s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "350MB"

networks:
  rinha-network:
    driver: bridge
